# Generated by Django 4.2.7 on 2023-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afisha',
            name='created_ad',
            field=models.DateField(null=True),
        ),
    ]
