# Generated by Django 4.2.7 on 2023-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_afisha_created_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(null=True, upload_to='car_slider'),
        ),
    ]
