# Generated by Django 4.2.7 on 2023-11-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_slider_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.URLField(),
        ),
    ]
